import type { Metadata } from "next";
import { Inter } from 'next/font/google'

import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Wallbit challenge",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${inter.className}  antialiased grid grid-rows-[auto,1fr,auto] min-h-screen dark`}
      >
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        > */}
        <Toaster />
        <header className="border-b border-b-border py-4">
          <div
            className="max-w-5xl mx-auto"
          >
            <h1 className="text-4xl font-bold">Tienda wallbit</h1>
            {/* <ModeToggle /> */}
          </div>
        </header>
        {children}
        <footer className="border-t border-t-border py-4 text-center">
          Con 🖤, Fede.
        </footer>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
